# docker-pypa-build - Docker configuration for PyPA's build
# Written in 2024 by Hubert Bielenia <13271065+hbielenia@users.noreply.github.com>
# To the extent possible under law, the author(s) have dedicated all copyright and related
# and neighboring rights to this software to the public domain worldwide. This software
# is distributed without any warranty.
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

name: docker
on:
  workflow_call:
    inputs:
      latest:
        type: boolean
        default: false
      push:
        type: boolean
        default: false
      python_version_major:
        type: number
        default: 3
      python_version_minor:
        type: number
        required: true
      python_version_patch:
        type: number
        required: true
env:
  BUILD_VERSION_MINOR: '1.2'
  BUILD_VERSION_PATCH: '2'
  PYTHON_VERSION: '${{ inputs.python_version_major }}.${{ inputs.python_version_minor }}'
  DEBIAN_VERSION: bullseye
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_USERNAME }}/pypa-build
  GHCR_REPO: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Docker image
        uses: hbielenia/docker-build-action@7211d36e8ed0a62e6ef2f8610b734896e93d8190 # 0.2.0
        with:
          dockerfile: ./dockerfiles/${{ env.DEBIAN_VERSION }}/python-${{ env.PYTHON_VERSION }}.Dockerfile
          tags: ${{ env.DOCKERHUB_REPO }}:latest
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          persist-credentials: false
      - name: Run test script
        run: ./test_image.sh
  upload:
    if: inputs.push
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # 3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # 3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: hbielenia/docker-build-action@7211d36e8ed0a62e6ef2f8610b734896e93d8190 # 0.2.0
        with:
          dockerfile: ./dockerfiles/${{ env.DEBIAN_VERSION }}/python-${{ env.PYTHON_VERSION }}.Dockerfile
          from_cache: '1'
          push: '1'
          tags: >-
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_VERSION }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }}-${{ env.DEBIAN_VERSION }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_VERSION }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }}-${{ env.DEBIAN_VERSION }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_VERSION }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }}-${{ env.DEBIAN_VERSION }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_VERSION }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }}-py${{ env.PYTHON_VERSION }}.${{ inputs.python_version_patch }}-${{ env.DEBIAN_VERSION }},
      - name: Push generic tags
        if: inputs.latest
        uses: hbielenia/docker-build-action@7211d36e8ed0a62e6ef2f8610b734896e93d8190 # 0.2.0
        with:
          dockerfile: ./dockerfiles/${{ env.DEBIAN_VERSION }}/python-${{ env.PYTHON_VERSION }}.Dockerfile
          from_cache: '1'
          push: '1'
          tags: >-
            ${{ env.DOCKERHUB_REPO }}:latest,
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }},
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }},
            ${{ env.GHCR_REPO }}:latest,
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }},
            ${{ env.GHCR_REPO }}:${{ env.BUILD_VERSION_MINOR }}.${{ env.BUILD_VERSION_PATCH }},
